In [1]:
import open3d as o3d

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


INFO - 2022-10-04 13:26:47,119 - utils - Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO - 2022-10-04 13:26:47,120 - utils - NumExpr defaulting to 8 threads.


In [2]:
!pip install plotly

     |████████████████████████████████| 15.2 MB 45 kB/s  eta 0:00:01


In [3]:
# Reference: https://colab.research.google.com/drive/1CR_HDvJ2AnjJV3Bf5vwP70K0hx3RcdMb?usp=sharing

import plotly.graph_objects as go

def draw_geometries(geometries):
    graph_objects = []

    for geometry in geometries:
        geometry_type = geometry.get_geometry_type()
        
        if geometry_type == o3d.geometry.Geometry.Type.PointCloud:
            points = np.asarray(geometry.points)
            colors = None
            if geometry.has_colors():
                colors = np.asarray(geometry.colors)
            elif geometry.has_normals():
                colors = (0.5, 0.5, 0.5) + np.asarray(geometry.normals) * 0.5
            else:
                geometry.paint_uniform_color((1.0, 0.0, 0.0))
                colors = np.asarray(geometry.colors)

            scatter_3d = go.Scatter3d(x=points[:,0], y=points[:,1], z=points[:,2], mode='markers', marker=dict(size=1, color=colors))
            graph_objects.append(scatter_3d)

        if geometry_type == o3d.geometry.Geometry.Type.TriangleMesh:
            triangles = np.asarray(geometry.triangles)
            vertices = np.asarray(geometry.vertices)
            colors = None
            if geometry.has_triangle_normals():
                colors = (0.5, 0.5, 0.5) + np.asarray(geometry.triangle_normals) * 0.5
                colors = tuple(map(tuple, colors))
            else:
                colors = (1.0, 0.0, 0.0)
            
            mesh_3d = go.Mesh3d(x=vertices[:,0], y=vertices[:,1], z=vertices[:,2], i=triangles[:,0], j=triangles[:,1], k=triangles[:,2], facecolor=colors, opacity=0.50)
            graph_objects.append(mesh_3d)
        
    fig = go.Figure(
        data=graph_objects,
        layout=dict(
            scene=dict(
                xaxis=dict(visible=False),
                yaxis=dict(visible=False),
                zaxis=dict(visible=False)
            )
        )
    )
    fig.show()

In [4]:
o3d.visualization.draw_geometries = draw_geometries # replace function

In [7]:
ply_filename = './3rdparty/Open3D/examples/test_data/bathtub_0154.ply'

In [8]:
import numpy as np
import open3d as o3d

print("Loading a point cloud from", ply_filename)
pcd = o3d.io.read_point_cloud(ply_filename)

print(pcd)
print(np.asarray(pcd.points))

o3d.visualization.draw_geometries([pcd])

Loading a point cloud from ./3rdparty/Open3D/examples/test_data/bathtub_0154.ply
PointCloud with 1494 points.
[[ -9208.08007812  19354.84960938  -6295.04980469]
 [ -1696.69995117  -3551.25        -6295.04980469]
 [  9129.29980469  19354.84960938  -6295.04980469]
 ...
 [ 14763.79980469  33464.55078125  13005.90039062]
 [ 14763.79980469 -33464.55078125   9068.90039062]
 [ 14763.79980469  33464.55078125   9068.90039062]]
